baseurl = "https://sallyom.github.io/"
title = "This is my blog..."
copyright = "Copyright &copy; 2020-2025 - Sally Ann O'Malley"
canonifyurls = true
theme = "hugo-kiera"

[pagination]
pagerSize = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    github = "sallyom"
    #gitlab = "username"
    #linkedin = "sally-ann-omalley"
    #facebook = "username"
    twitter = "somalley108"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "This is my blog."
    description = "A collection of stuff I've learned."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = ["css/custom.css"]  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 1

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 2

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 3
